### ISSUE TITLE
Output geometry as GeoJSON

### ISSUE THREAD

**Issue by timwis** [timwis/soda-postgres#1]
Per [Point Datatype docs](http://dev.socrata.com/docs/datatypes/point.html), geometry should be output as GeoJSON. The problem is when applying this to any table in the DB, we don't know which field is geometry, so `SELECT *` outputs geometry in binary format.

Idea:
1. Before any query, get a description of the table and store the fields and their types in a js object
2. Replace `SELECT *` with `SELECT field, field, field` from the js object
3. Iterate through the SELECT columns in the AST and check if any are of type "geometry" -- if so, add the `ST_AsGeoJSON` function to them

The downside here is that step 1 happens before every query -- ideally we'd cache it. But perhaps caching can come later.

**Comment by timwis** [comment]
Did the above and it's working. I also had to do a string replace on the compiled SQL to replace `ST_AsGeoJSON(xxx)` with `ST_AsGeoJSON(xxx)::json` since it was returning a string of GeoJSON instead of actual JSON. Feels pretty hacky.

**Comment by gsf** [comment]
Looks like the commit covering this change is 060ac4997ec60b36c5a1cd28862ce700a95577b1.

**Comment by timwis** [comment]
Yeah-  just wondering if there's a better/less hacky way to do it, but can't think of one

**Comment by gsf** [comment]
My thought in looking at this is that it might be handled better in node-soda2-parser -- could there be a generic way to recognize "geometry" and output it as JSON in the parse and stringify methods there?
